# Generated by Django 2.2 on 2020-08-30 06:06

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perName', models.CharField(max_length=256)),
                ('engName', models.CharField(max_length=256)),
                ('basePrice', models.FloatField()),
                ('currentPrice', models.FloatField(null=True)),
                ('brand', models.CharField(max_length=256)),
                ('store', models.CharField(max_length=256)),
                ('rating', models.FloatField(null=True)),
                ('warranty', models.CharField(max_length=256, null=True)),
                ('description', models.TextField()),
                ('amazing', models.BooleanField(default=False, null=True)),
                ('discountPercent', models.IntegerField(default=0, null=True)),
                ('colors', models.ManyToManyField(null=True, related_name='colors', to='product.Color')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=product.models.imageSavePath)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product')),
            ],
        ),
    ]
