# Generated by Django 2.2 on 2020-08-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
