# Generated by Django 2.2 on 2020-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_amazing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountPercent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
