# Generated by Django 2.2 on 2020-09-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200830_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(error_messages={'unique': 'این دسته بندی هم اکنون موجود می باشد'}, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(error_messages={'unique': 'این دسته بندی هم اکنون موجود می باشد'}, max_length=256, unique=True),
        ),
    ]
