# Generated by Django 2.2 on 2020-08-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20200803_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='main_category',
        ),
    ]
