# Generated by Django 2.2 on 2020-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200729_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_boss',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
